# You_can_find_more_information_about_this_file_on_the_symfony_website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default_values
all:
  commerciaux:
    liste:
      Eliott: 10
  situations:
    liste:
      ATT_CONFIRMATION:   "ATT PROFORMA" # Statut structurant
      EN_COURS:           "IN PROCESS"   # Statut structurant
      SOLDEE:             "SOLDÉE"       # Statut structurant
      RETARD_LIVRAISON:   "RETARD"
      ATTENTE_PAIEMENT:   "ATTENTE PAIEMENT AVT EXP"
      DEPOSIT_EN_ATTENTE:  "DEPOSIT EN ATTENTE"
      DEPOSIT_RECU:   "DEPOSIT REÇU"
  paiements:
    liste:
      VIREMENT_30_JOURS: "Virement 30 jours"
      VIREMENT_60_JOURS: "Virement 60 jours"
      VIREMENT_90_JOURS: "Virement 90 jours"
  conditions_paiement:
    liste:
      30_JOURS_NET: "30 JOURS NET"
      30_JOURS_FIN_DE_MOIS: "30 JOURS FIN DE MOIS"
      60_JOURS_NET: "60 JOURS NET"
      60_JOURS_FIN_DE_MOIS: "60 JOURS FIN DE MOIS"
      90_JOURS_NET: "90 JOURS NET"
      90_JOURS_FIN_DE_MOIS: "90 JOURS FIN DE MOIS"
      PAIEMENT_AVANCE: "PAIEMENT DAVANCE AVANT EXPEDITION 100 %"
      PAIEMENT_AVANCE_30_COMMANDE_70_ENVOI: "PAIEMENT DAVANCE 30 % DEPOSIT 70 % BEFORE DEPARTURE"
      LC: "L/C"
      LC_A_30_JOURS: "L/C 30 JOURS"
      LC_A_45_JOURS: "L/C 45 JOURS"
      LC_A_75_JOURS: "L/C 75 JOURS"
      LC_A_90_JOURS: "L/C 90 JOURS"
  statuts:
    liste:
      REFUS: "Refus"
      EN_ATTENTE: "En attente"
      VALIDE: "Validé"
  statuts_lab_dip:
    liste:
      EN_COURS: "En cours"
      EXPE_CLIENT: "Expé client"
      REFUSE: "Refusé"
      ANNULE: "Annulé"
      VALIDE: "Validé"
  statuts_facture:
    liste:
      #EN_ATTENTE: "En attente"
      #ECHUE: "Echue"
      PAYEE: "Payée"
      NON_PAYEE: "Non payée"
      #ERREUR: "Erreur"
  statuts_credit:
    liste:
      EN_ATTENTE: "En attente"
      DEDUITE: "Deduite"
  piece_categories:
    liste:
      DOUBLE_FACE: "Double face"
      MAILLE: "Maille"
      DOUDOUNE: "Doudoune"
      PARKAS: "Parkas"
      ROBE: "Robe"
      BLOUSON: "Blouson"
      VESTE: "Veste"
      TRENCH: "Trench"
      PANTALON: "Pantalon / Short"
      PAILLETTES: "Paillettes"
      JUPE: "Jupe"
      COMBINAISON: "Combinaison"
      CHEMISES: "Chemises / Blouses / Top"
      MAILLOT_BAIN: "Maillot de bain"
      AUTRE: "Autre"
      ECHARPRES: "Echarpes"
      BONNETS: "Bonnets"
      GANTS: "Gants"
      MAROQUINERIE: "Maroquinerie"
      PONCHOS: "Ponchos"
      PLAIDS: "Plaids"
  devise:
    dollar: true
  no_metrage: true
