# You_can_find_more_information_about_this_file_on_the_symfony_website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default_values
all:
  commerciaux:
    liste:
      Eliott: 10
  situations:
    liste:
      ATT_CONFIRMATION:   "ATT PROFORMA" # Statut structurant
      EN_COURS:           "IN PROCESS"   # Statut structurant
      SOLDEE:             "SOLDÉE"       # Statut structurant
      RETARD_LIVRAISON:   "RETARD"
      ATTENTE_PAIEMENT:   "ATTENTE PAIEMENT AVT EXP"
      DEPOSIT_EN_ATTENTE:  "DEPOSIT EN ATTENTE"
      DEPOSIT_RECU:   "DEPOSIT REÇU"
  paiements:
    liste:
      VIREMENT_30_JOURS: "Virement 30 jours"
      VIREMENT_60_JOURS: "Virement 60 jours"
      VIREMENT_90_JOURS: "Virement 90 jours"
  conditions_paiement:
    liste:
      30_JOURS_NET: "30 JOURS NET"
      30_JOURS_FIN_DE_MOIS: "30 JOURS FIN DE MOIS"
      60_JOURS_NET: "60 JOURS NET"
      60_JOURS_FIN_DE_MOIS: "60 JOURS FIN DE MOIS"
      90_JOURS_NET: "90 JOURS NET"
      90_JOURS_FIN_DE_MOIS: "90 JOURS FIN DE MOIS"
      PAIEMENT_AVANCE: "PAIEMENT DAVANCE AVANT EXPEDITION 100 %"
      PAIEMENT_AVANCE_30_COMMANDE_70_ENVOI: "PAIEMENT DAVANCE 30 % DEPOSIT 70 % BEFORE DEPARTURE"
      LC: "L/C"
      LC_A_30_JOURS: "L/C 30 JOURS"
      LC_A_45_JOURS: "L/C 45 JOURS"
      LC_A_75_JOURS: "L/C 75 JOURS"
      LC_A_90_JOURS: "L/C 90 JOURS"
  statuts:
    liste:
      REFUS: "Refus"
      EN_ATTENTE: "En attente"
      VALIDE: "Validé"
  statuts_lab_dip:
    liste:
      EN_COURS: "En cours"
      EXPE_CLIENT: "Expé client"
      REFUSE: "Refusé"
      ANNULE: "Annulé"
      VALIDE: "Validé"
  statuts_facture:
    liste:
      #EN_ATTENTE: "En attente"
      #ECHUE: "Echue"
      PAYEE: "Payée"
      NON_PAYEE: "Non payée"
      #ERREUR: "Erreur"
  statuts_credit:
    liste:
      EN_ATTENTE: "En attente"
      DEDUITE: "Deduite"
  piece_categories:
    liste:
        DOUBLEFACE_MANTEAU: "MANTEAU (DOUBLE FACE)"
        DOUBLEFACE_VESTE: "VESTE (DOUBLE FACE)"
        DOUBLEFACE_GILET:  "GILET (DOUBLE FACE)"
        DOUBLEFACE_TOP: "TOP (DOUBLE FACE)"
        DOUBLEFACE_CAPE: "CAPE (DOUBLE FACE)"
        DOUBLEFACE_JUPE: "JUPE (DOUBLE FACE)"
        DOUBLEFACE_ROBE: "ROBE (DOUBLE FACE)"
        DOUBLEFACE_SURCHEMISE: "SURCHEMISE (DOUBLE FACE)"
        DOUBLEFACE_PONCHOS: "PONCHOS (DOUBLE FACE)"
        DOUBLEFACE_ACCESSOIRES: "ACCESSOIRES (DOUBLE FACE)"
        MAILLE_GILET: "GILET (MAILLE)"
        MAILLE_TOP: "TOP (MAILLE)"
        MAILLE_PULL: "PULL (MAILLE)"
        MAILLE_JUPE: "JUPE (MAILLE)"
        MAILLE_ROBE: "ROBE (MAILLE)"
        MAILLE_ACCESSOIRES: "ACCESSOIRES (MAILLE)"
        JERSEY_TSHIRT: "TSHIRT (JERSEY)"
        JERSEY_ROBE: "ROBE (JERSEY)"
        JERSEY_PANTALON: "PANTALON (JERSEY)"
        DOUDOUNE_DOUDOUNE: "DOUDOUNE"
        PARK_PARKA: "PARKA"
        TRENCH_TRENCH: "TRENCH"
        FLOU_TOP: "TOP (FLOU)"
        FLOU_CHEMISE: "CHEMISE (FLOU)"
        FLOU_VESTE: "VESTE (FLOU)"
        FLOU_TRENCH: "TRENCH (FLOU)"
        FLOU_PANTALON: "PANTALON (FLOU)"
        FLOU_SHORT: "SHORT (FLOU)"
        FLOU_PAILLETTES: "PAILLETTES (FLOU)"
        FLOU_JUPE: "JUPE (FLOU)"
        FLOU_COMBINAISON: "COMBINAISON (FLOU)"
        FLOU_ACCESSOIRES: "ACCESSOIRES (FLOU)"
        PAILLETTE_ROBE: "ROBE (PAILLETTE)"
        PAILLETTE_TOP: "TOP (PAILLETTE)"
        PAILLETTE_VESTE: "VESTE (PAILLETTE)"
        MAROQUINERIE: "MAROQUINERIE"
        FAKEFUR_VESTE: "VESTE (FAKE FUR)"
        FAKEFUR_MANTEAU: "MANTEAU (FAKE FUR)"
        PEAUXLAINE_VESTE: "VESTE (PEAUX LAINE)"
        PEAUXLAINE_MANTEAU: "MANTEAU (PEAUX LAINE)"
        PEAUXLAINE_GILET: "GILET (PEAUX LAINE)"
        CUIR_VESTE: "VESTE (CUIR)"
        CUIR_MANTEAU: "MANTEAU (CUIR)"
        CUIR_PANTALON: "PANTALON (CUIR)"
        CUIR_TOP: "TOP (CUIR)"
        CUIR_GILET: "GILET (CUIR)"
  devise:
    dollar: true
  no_metrage: true
