generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Fournisseur
    theme:                 nathanmode
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fournisseur
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: {}
        actions:
          csv: { label: "CSV" }
          _new: ~
        title: "Liste des fournisseurs"
        display: [raison_sociale, prenom, telephone, commission, Devise]
      filter:
        display: [raison_sociale, prenom, telephone, commission, devise_id]
      form:
        display: [raison_sociale, prenom, telephone, commission, devise_id]
      edit:
        title: "Modification du fournisseur %%raison_sociale%%"
      new:
        title: "Nouveau fournisseur"
